[signing]
backend = "ssh"
behavior = "own"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC/qhn9neDAsXF7tbLp+sao9P1YFq5/2pTIo5L/I5FFU"

[signing.backends.ssh]
program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[user]
email = "63924603+heyglassy@users.noreply.github.com"
name = "Christian Glassiognon"
